#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
repack_vendor_boot.py — Xiaomi rothko (MT6989) vendor_boot v4 repacker.

Replaces the RECOVERY vendor ramdisk fragment of a stock vendor_boot v4
image with a new recovery ramdisk, compressing it explicitly, and rebuilds
the fragment table + AVB-free image body. Run avbtool afterwards to add the
hash footer.

Why this exists
---------------
`magiskboot repack` reuses the compression format detected at *unpack*
time; it does NOT honour a MAGISKBOOT_COMPRESS environment variable. When
a fresh mkbootfs cpio is handed to `magiskboot repack`, the cpio magic
(070701) is detected as "raw" and the ramdisk is stored UNCOMPRESSED,
producing:

    avbtool: Adding hash_footer failed: Image size of 70012928 exceeds
    maximum image size of 67039232 in order to fit in a partition size
    of 67108864.

This tool compresses explicitly. A ~70 MiB ramdisk that magiskboot stored
raw becomes ~25 MiB with gzip, which fits the 64 MiB vendor_boot partition
next to the untouched 41 MiB stock platform fragment.

Verified stock header layout (prebuilt/stock_vendor_boot.img, byte offsets):
      0  magic "VNDRBOOT"
      8  header_version = 4
     12  page_size = 4096
     24  vendor_ramdisk_size
     28  cmdline[2048]
   2076  tags_addr
   2080  name[16]
   2096  header_size = 2128
   2100  dtb_size
   2104  dtb_addr (u64)
   2112  (vendor field, = entry_num*entry_size in stock; preserved verbatim)
   2116  ramdisk_table_entry_num
   2120  ramdisk_table_entry_size
   2124  ramdisk_table_offset region — ZERO in stock: the bootloader locates
         the table from the section layout, so the repacker recomputes it
         the same way (header page is copied verbatim except
         vendor_ramdisk_size).

Image layout (page-aligned sections, in order):
    [ header ][ vendor ramdisk fragments ][ dtb ][ fragment table ]
    [ bootconfig region ][ AVB vbmeta (regenerated by avbtool) ]

The stock bootconfig region (between the table page and the AVB0 vbmeta
magic) is copied verbatim, so vendor-bootloader-visible content other than
the recovery ramdisk is byte-identical to stock.

Usage
-----
    # inspect a vendor_boot image
    python3 tools/repack_vendor_boot.py --check prebuilt/stock_vendor_boot.img

    # dump the raw (still-compressed) fragments
    python3 tools/repack_vendor_boot.py --dump-fragments DIR stock.img

    # replace the recovery fragment with a new cpio (compressed here)
    python3 tools/repack_vendor_boot.py \
        --stock prebuilt/stock_vendor_boot.img \
        --recovery-cpio new_ramdisk.cpio \
        --output vendor_boot.img --compress gzip

    The vendor_boot cmdline gets "androidboot.selinux=permissive"
    appended if missing (same as the on-device installer's
    VendorBootImage.ensureCmdlineToken()); pass --cmdline-token "" to
    leave the cmdline untouched, or a custom token to append that one.

    # replace with an already-compressed fragment (round-trip testing)
    python3 tools/repack_vendor_boot.py \
        --stock prebuilt/stock_vendor_boot.img \
        --recovery-fragment recovery.bin \
        --output vendor_boot.img

    # also recompress the platform fragment if space is still tight
    # (requires the stock fragment to be decompressible: gzip/lz4 tools)
    python3 tools/repack_vendor_boot.py ... --recompress-platform

Afterwards sign as usual, e.g.:
    avbtool add_hash_footer --image vendor_boot.img \
        --partition_size 67108864 --partition_name vendor_boot ...
"""

import argparse
import os
import struct
import subprocess
import sys
import tempfile

VNDRBOOT_MAGIC = b"VNDRBOOT"
AVB_VBMETA_MAGIC = b"AVB0"

# Offsets in the stock v4 header (see module docstring)
OFF_VENDOR_RAMDISK_SIZE = 24
OFF_DTB_SIZE = 2100
OFF_ENTRY_NUM = 2116
OFF_ENTRY_SIZE = 2120
OFF_CMDLINE = 28
CMDLINE_SIZE = 2048

# The on-device installer (com.ccccclovemiku.rothkoinstaller) requires
# this token in the vendor_boot cmdline; ensureCmdlineToken() appends it
# when missing. Keep parity so images repacked here behave identically.
DEFAULT_CMDLINE_TOKEN = "androidboot.selinux=permissive"

# vendor_ramdisk_table_entry: ramdisk_size, ramdisk_offset, ramdisk_type,
# ramdisk_name[32], board_id[16] (u32 each, as in AOSP bootimg.h)
ENTRY_HEAD_FMT = "<III"
ENTRY_NAME_OFF = 12
ENTRY_NAME_LEN = 32
FULL_ENTRY_SIZE = 108  # as found in the stock image

VENDOR_RAMDISK_TYPE = {
    0: "none",
    1: "platform",
    2: "recovery",
    3: "dlkm",
}
TYPE_RECOVERY = 2

GZIP_MAGIC = b"\x1f\x8b"
LZ4_FRAME_MAGIC = b"\x04\x22\x4d\x18"
LZ4_LEGACY_MAGIC = b"\x02\x21\x4c\x18"
CPIO_MAGIC = b"070701"

# avbtool reserves this much of the partition for the vbmeta blob, hash
# descriptor and footer (partition_size - max_image_size from the CI failure:
# 67108864 - 67039232).
AVB_RESERVED = 69632


def pages(n, ps):
    return (n + ps - 1) // ps


def pad_to(data, ps):
    rem = len(data) % ps
    return data if rem == 0 else data + b"\x00" * (ps - rem)


def detect_compression(blob):
    if blob[:2] == GZIP_MAGIC:
        return "gzip"
    if blob[:4] == LZ4_FRAME_MAGIC:
        return "lz4"
    if blob[:4] == LZ4_LEGACY_MAGIC:
        return "lz4-legacy"
    return "raw"


def run_tool(cmd, stdin_data=None):
    p = subprocess.run(cmd, stdout=subprocess.PIPE,
                       input=stdin_data)
    if p.returncode != 0:
        raise RuntimeError("command failed (%d): %s" %
                           (p.returncode, " ".join(cmd)))
    return p.stdout


def gzip_compress(data):
    """Pure-python gzip (RFC 1952), level 9, no name/timestamp.

    Equivalent to `gzip -9n`; avoids depending on an external gzip binary
    so the tool also runs on Windows/macOS.
    """
    import zlib
    co = zlib.compressobj(9, zlib.DEFLATED, -zlib.MAX_WBITS)
    deflated = co.compress(data) + co.flush()
    # header: magic, deflate, no flags, mtime=0, XFL=2 (best compression),
    # OS=255 (unknown)
    return (b"\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff" + deflated +
            struct.pack("<II", zlib.crc32(data) & 0xFFFFFFFF, len(data) & 0xFFFFFFFF))


def compress(data, algo):
    """Compress *data* with the given algorithm."""
    if algo == "gzip":
        return gzip_compress(data)
    if algo not in ("lz4", "lz4-legacy"):
        raise ValueError("cannot compress with algo %r" % algo)
    with tempfile.TemporaryDirectory() as td:
        src = os.path.join(td, "in.bin")
        with open(src, "wb") as f:
            f.write(data)
        dst = os.path.join(td, "out.bin")
        cmd = (["lz4", "-9", "-f"] if algo == "lz4"
               else ["lz4", "-l", "-9", "-f"])
        run_tool(cmd + [src, dst])
        with open(dst, "rb") as f:
            return f.read()


def decompress(blob, algo):
    """Decompress *blob* (needed only for --recompress-platform)."""
    with tempfile.TemporaryDirectory() as td:
        src = os.path.join(td, "in.bin")
        with open(src, "wb") as f:
            f.write(blob)
        if algo == "gzip":
            return run_tool(["gzip", "-dc", src])
        dst = os.path.join(td, "out.bin")
        with open(src, "rb") as f, open(dst, "wb") as g:
            g.write(b"")  # truncate
        run_tool(["lz4", "-df", src, dst])
        with open(dst, "rb") as f:
            return f.read()


def ensure_cmdline_token(header, token):
    """Append *token* to the boot cmdline in *header* (bytearray) if absent.

    Mirrors VendorBootImage.ensureCmdlineToken() of the on-device
    installer: the token must not contain whitespace, is matched as a
    whole cmdline token (not a substring), and is appended with a single
    separating space before the existing NUL padding. Returns True if
    the header was modified.
    """
    if not token:
        return False
    if any(c in token for c in " \t\r\n"):
        raise ValueError("cmdline token contains whitespace: %r" % token)

    raw = bytes(header[OFF_CMDLINE:OFF_CMDLINE + CMDLINE_SIZE])
    nul = raw.find(b"\x00")
    if nul < 0:
        raise ValueError("cmdline has no NUL terminator (corrupt header)")
    current = raw[:nul].decode("ascii", "replace")

    if token in current.split():
        return False

    addition = (" " if current else "") + token
    if nul + len(addition) + 1 > CMDLINE_SIZE:
        raise ValueError("cmdline too long to append %r (%d+%d > %d)"
                         % (token, nul, len(addition), CMDLINE_SIZE))

    start = OFF_CMDLINE + nul
    header[start:start + len(addition)] = addition.encode("ascii")
    header[start + len(addition)] = 0  # keep it NUL-terminated
    return True


class Fragment(object):
    def __init__(self, raw, blob):
        self.raw = bytearray(raw)   # full table entry (mutable)
        self.blob = blob            # fragment bytes as stored (compressed)
        self.size, self.offset, self.type = struct.unpack_from(
            ENTRY_HEAD_FMT, bytes(raw), 0)
        self.name = bytes(raw[ENTRY_NAME_OFF:
                              ENTRY_NAME_OFF + ENTRY_NAME_LEN]
                          ).split(b"\x00")[0].decode("ascii", "replace")

    @property
    def type_name(self):
        return VENDOR_RAMDISK_TYPE.get(self.type, "type%d" % self.type)

    def __repr__(self):
        return "<Fragment %s(%s) offset=%d size=%d comp=%s>" % (
            self.name or "-", self.type_name, self.offset, self.size,
            detect_compression(self.blob))


class VendorBootImage(object):
    def __init__(self, path):
        self.path = path
        with open(path, "rb") as f:
            self.data = f.read()
        d = self.data

        if d[:len(VNDRBOOT_MAGIC)] != VNDRBOOT_MAGIC:
            raise ValueError("%s: bad magic (not a vendor_boot image)" % path)

        (self.header_version, self.page_size) = struct.unpack_from("<IH", d, 8)
        self.vendor_ramdisk_size = struct.unpack_from("<I", d, 24)[0]
        self.dtb_size = struct.unpack_from("<I", d, OFF_DTB_SIZE)[0]
        self.entry_num = struct.unpack_from("<I", d, OFF_ENTRY_NUM)[0]
        self.entry_size = struct.unpack_from("<I", d, OFF_ENTRY_SIZE)[0]

        if self.header_version != 4:
            raise ValueError("%s: vendor_boot v%d not supported (need v4)"
                             % (path, self.header_version))

        ps = self.page_size

        # Sections. NOTE: the stock header's table-offset field is ZERO —
        # the bootloader derives the table position from the layout, so the
        # repacker computes it identically.
        self.ramdisk_blob = d[ps:ps + self.vendor_ramdisk_size]

        dtb_start = ps + ps * pages(self.vendor_ramdisk_size, ps)
        self.dtb = d[dtb_start:dtb_start + self.dtb_size]

        self.table_offset = (dtb_start + ps * pages(self.dtb_size, ps))
        table_len = self.entry_num * self.entry_size
        self.table = d[self.table_offset:self.table_offset + table_len]

        # Tail region (bootconfig etc.): everything from the page after the
        # table up to the AVB vbmeta blob (excluded — avbtool regenerates it)
        self.table_end_page = self.table_offset + ps * pages(table_len, ps)
        self.vbmeta_offset = d.find(AVB_VBMETA_MAGIC, self.table_end_page)
        if self.vbmeta_offset < 0:
            # No AVB in this image; tail is everything that remains non-zero
            self.vbmeta_offset = len(d)
        self.tail = d[self.table_end_page:self.vbmeta_offset]

        # Parse fragment entries (table order preserved)
        self.fragments = []
        for i in range(self.entry_num):
            raw = self.table[i * self.entry_size:(i + 1) * self.entry_size]
            size, offset, _ = struct.unpack_from(ENTRY_HEAD_FMT, raw, 0)
            blob = self.ramdisk_blob[offset:offset + size]
            self.fragments.append(Fragment(raw, blob))

    def summary(self):
        lines = [
            "image       : %s (%d bytes)" % (self.path, len(self.data)),
            "header ver  : %d, page_size %d" % (
                self.header_version, self.page_size),
            "vendor_ramdisk_size    : %d" % self.vendor_ramdisk_size,
            "dtb_size    : %d" % self.dtb_size,
            "table       : %d entries x %d bytes at offset %d (computed)" % (
                self.entry_num, self.entry_size, self.table_offset),
            "tail region : %d bytes (bootconfig etc., %d..%d)" % (
                len(self.tail), self.table_end_page, self.vbmeta_offset),
            "fragments   :",
        ]
        for i, fr in enumerate(self.fragments):
            lines.append("  [%d] %-9s name=%-16s offset=%-9d size=%-9d "
                         "stored as %s" % (
                             i, fr.type_name, fr.name or "-", fr.offset,
                             fr.size, detect_compression(fr.blob)))
        return "\n".join(lines)

    def recovery_fragments(self):
        return [f for f in self.fragments if f.type == TYPE_RECOVERY]

    def rebuild(self, fragment_blobs, cmdline_token=DEFAULT_CMDLINE_TOKEN):
        """Return new image bytes with fragments replaced.

        fragment_blobs: list of (fragment, new_blob) pairs. Fragments not
        listed keep their stock blob. The header page is copied verbatim
        except vendor_ramdisk_size and, when *cmdline_token* is non-empty,
        the boot cmdline (token appended if missing — see
        ensure_cmdline_token()); the tail (bootconfig region) is copied
        verbatim; the AVB vbmeta/footer is NOT copied (avbtool regenerates).
        """
        ps = self.page_size
        replace = {id(fr): blob for fr, blob in fragment_blobs}

        ordered = sorted(self.fragments, key=lambda f: f.offset)
        new_blob = bytearray()
        for fr in ordered:
            data = replace.get(id(fr), fr.blob)
            struct.pack_into("<II", fr.raw, 0, len(data), len(new_blob))
            fr.size, fr.offset = len(data), len(new_blob)
            new_blob += data

        header = bytearray(self.data[:ps])
        struct.pack_into("<I", header, OFF_VENDOR_RAMDISK_SIZE, len(new_blob))
        if cmdline_token:
            if ensure_cmdline_token(header, cmdline_token):
                print("[*] cmdline: appended token %r" % cmdline_token)
            else:
                print("[*] cmdline: token %r already present" % cmdline_token)

        # Entries keep their original table order; their raw bytes were
        # patched in place above.
        new_table = b"".join(bytes(fr.raw) for fr in self.fragments)

        out = bytearray()
        out += header
        out += pad_to(bytes(new_blob), ps)
        out += pad_to(self.dtb, ps)
        out += pad_to(new_table, ps)
        out += pad_to(self.tail, ps)
        return bytes(out)


def main():
    ap = argparse.ArgumentParser(
        description="vendor_boot v4 repacker for rothko (Xiaomi 14T Pro / "
                    "Redmi K70 Ultra)")
    ap.add_argument("image", nargs="?",
                    help="vendor_boot image to inspect (--check/--dump-fragments)")
    ap.add_argument("--check", action="store_true",
                    help="print header/fragment info and exit")
    ap.add_argument("--dump-fragments", metavar="DIR",
                    help="write each raw fragment blob to DIR")
    ap.add_argument("--stock", help="stock vendor_boot image (repack base)")
    ap.add_argument("--recovery-cpio",
                    help="new recovery ramdisk as an uncompressed newc cpio "
                         "(will be compressed)")
    ap.add_argument("--recovery-fragment",
                    help="new recovery fragment blob that is ALREADY "
                         "compressed (no compression applied)")
    ap.add_argument("--recompress-platform", action="store_true",
                    help="additionally recompress the stock platform "
                         "fragment with --compress (big extra savings; "
                         "requires gzip/lz4 tools)")
    ap.add_argument("--output", help="output image path")
    ap.add_argument("--cmdline-token", default=DEFAULT_CMDLINE_TOKEN,
                    metavar="TOKEN",
                    help="boot cmdline token to append if missing "
                         "(default: %r, as required by the on-device "
                         "installer; pass an empty string to disable)"
                         % DEFAULT_CMDLINE_TOKEN)
    ap.add_argument("--compress", default="auto",
                    choices=["auto", "gzip", "lz4", "lz4-legacy"],
                    help="compression for the new recovery ramdisk; 'auto' "
                         "matches the stock recovery fragment's format "
                         "(default)")
    ap.add_argument("--partition-size", type=int, default=67108864,
                    help="vendor_boot partition size for the size check "
                         "(default 67108864 = 64 MiB)")
    args = ap.parse_args()

    if args.check or args.dump_fragments:
        if not args.image:
            ap.error("--check/--dump-fragments need an image argument")
        img = VendorBootImage(args.image)
        print(img.summary())
        if args.dump_fragments:
            os.makedirs(args.dump_fragments, exist_ok=True)
            for i, fr in enumerate(img.fragments):
                fn = os.path.join(
                    args.dump_fragments,
                    "%d_%s%s.bin" % (i, fr.type_name,
                                     "_" + fr.name if fr.name else ""))
                with open(fn, "wb") as f:
                    f.write(fr.blob)
                print("dumped %s (%d bytes, %s)" % (
                    fn, len(fr.blob), detect_compression(fr.blob)))
        return 0

    if not (args.stock and args.output
            and (args.recovery_cpio or args.recovery_fragment)):
        ap.error("repack needs --stock, --output and either "
                 "--recovery-cpio or --recovery-fragment")

    img = VendorBootImage(args.stock)
    recs = img.recovery_fragments()
    if len(recs) != 1:
        ap.error("expected exactly 1 recovery fragment, found %d" % len(recs))
    old_rec = recs[0]

    replacements = []

    if args.recovery_fragment:
        with open(args.recovery_fragment, "rb") as f:
            new_blob = f.read()
        used = detect_compression(new_blob)
        if used == "raw":
            print("[!] warning: replacement fragment is not compressed")
    else:
        with open(args.recovery_cpio, "rb") as f:
            cpio = f.read()
        if cpio[:len(CPIO_MAGIC)] != CPIO_MAGIC:
            print("[!] warning: input does not start with cpio newc magic "
                  "(070701)")
        used = args.compress
        if used == "auto":
            used = detect_compression(old_rec.blob)
            if used == "raw":
                used = "gzip"
                print("[!] stock recovery fragment is uncompressed; "
                      "falling back to gzip")
        print("[*] compressing %d bytes of recovery cpio with %s ..." % (
            len(cpio), used))
        new_blob = compress(cpio, used)
    replacements.append((old_rec, new_blob))

    if args.recompress_platform:
        plats = [f for f in img.fragments if f.type != TYPE_RECOVERY]
        for plat in plats:
            algo = detect_compression(plat.blob)
            print("[*] recompressing platform fragment (%d bytes, %s -> %s)"
                  % (len(plat.blob), algo, args.compress
                     if args.compress != "auto" else "gzip"))
            raw = decompress(plat.blob, algo)
            pcomp = (args.compress if args.compress != "auto" else "gzip")
            replacements.append((plat, compress(raw, pcomp)))

    out = img.rebuild(replacements,
                      cmdline_token=args.cmdline_token)
    with open(args.output, "wb") as f:
        f.write(out)

    max_img = args.partition_size - AVB_RESERVED
    ok = len(out) <= max_img
    print("""
result
------
stock recovery fragment : %d bytes (%s)
new recovery fragment   : %d bytes (%s)
cmdline token           : %s
new image body          : %d bytes (AVB footer to be added by avbtool)
avbtool maximum         : %d bytes (partition %d - %d reserved)
status                  : %s (%d bytes %s)
""" % (len(old_rec.blob), detect_compression(old_rec.blob),
       len(new_blob), used,
       args.cmdline_token if args.cmdline_token else "(untouched)",
       len(out), max_img, args.partition_size,
       AVB_RESERVED, "OK, fits" if ok else "TOO BIG, will fail avbtool",
       abs(len(out) - max_img), "spare" if ok else "over"))
    if not ok:
        print("[!] tip: re-run with --recompress-platform to also shrink "
              "the 41 MiB stock platform fragment")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
